# Generated by Django 2.2.2 on 2019-06-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accumulate',
            field=models.IntegerField(default=0),
        ),
    ]
